### ISSUE TITLE
Packets Leak While Restarting Service?

### ISSUE THREAD

**Issue by Penguin-Guru** [triffid/pia-wg#14]
If I run a ping process while restarting or reloading the net.pia service, latency briefly drops down to non-proxy levels. Is there a simple fix for this? I may investigate a bit when I have time.

**Comment by triffid** [comment]
Can't do anything about restart since that involves stop (which removes the pia-wg interface) and then start.

Don't restart if you want to avoid leaks, use reload instead.

Restart exists solely to handle the case that something beyond the script's ability to automatically handle has happened to the pia-wg interface, and the easiest way to fix it is to tear it down and start from scratch.

This is the expected behaviour for restart vs reload in most services, so I'm not going to change it.

Reload was _specifically_ designed to not leak, in that it leaves the pia-wg interface active and just hot-reconfigures its remote peers - see https://github.com/triffid/pia-wg/blob/master/pia-wg.sh#L417-L454

**Comment by Penguin-Guru** [comment]
Got it. That does make sense. I just tested reload again and the ping rate did drop down to non-proxy levels, but apparently this proxy just happens to offer _much_ lower latency than most. Sorry for the confusion.

I occasionally run into a few minor issues that are probably not unexpected but which do sometimes require restarting the service. Things like needing to manually delete the token file, which the script requests. I do plan to dig deeper into the scripts at some point to figure them out. Until then, your explanation gives me peace of mind. :)

**Comment by triffid** [comment]
Yeah, the token thing is a bit strange - when I first wrote the scripts, they didn't seem to ever expire, so I made the script not require storing the account password.

If PIA is now expiring tokens periodically, then the execution path for detecting this and auto-fetching a new token using the stored password is kinda underdeveloped - feel free to send a pull req if that's what's happening ;)
